# Matricies and Numpy

## Introduction

Deep learning is riddled with matrix maths, so it is important to understand the basics

### Demensions of Data

Data can be of any number of Dimensions. For example, 
- **Scalars** are single data points, and have `0` dimensions
- **Vectors** are like lists of numbers, and have `1` dimension, the lenght of the vector
- **Matricies** are `2` dimensional, represented by their rows and columns
- **Tensors** are `n` demensional, all of the above are tensors too

## Data in numpy

The mosy common structure for all tensors in `ndarray` (n-dimensional array).

`ndarray`'s support very fast maths operations, whuch is awesome for us. 

In [2]:
import numpy as np

### Scalars

In [19]:
s = np.array(5) # A 0-dim Tensor, or SCALAR
print(type(s))
print(np.shape(s))    # One method
print(s.shape)        # `ndarray` is a class, and the shape is an attrib
print(s+2)            # As the tensor is a scalar, 
                      # it suports scalaer operations

<class 'numpy.ndarray'>
()
()
7


### Vectors

In [20]:
v = np.array([0,1,2,3])
print(type(v))
print(v.shape)        # `ndarray` is a class, and the shape is an attrib
print(v[1])           # Normal array indexing
print(v+2)            # As the tensor contains scalars, 
                      #      scalaer operations can be mapped over
print(v[1:])          # Used to select regions, ie 1 onwards

<class 'numpy.ndarray'>
(4,)
1
[2 3 4 5]
[1 2 3]


### Matricies

In [22]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(type(m))
print(m.shape)        # `ndarray` is a class, and the shape is an attrib
print(m[1])           # Normal array indexing
print(m[1][1])           # Normal array indexing
print(m+2)            # As the tensor contains scalars, 
                      #      scalaer operations can be mapped over
print(m[1:])          # Used to select regions, ie 1 onwards

<class 'numpy.ndarray'>
(3, 3)
[4 5 6]
5
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4 5 6]
 [7 8 9]]


### Tensors

In [25]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print(type(t))
print(t.shape)


<class 'numpy.ndarray'>
(3, 3, 2, 1)


Tensors and maticies also support an operation called `reshaping`. Reshaping can be uesd to change the shape of tensors. eg t.reshape(1,4) will turn a 4x1 matrix into a 1x4

## Element-wise operations in Matricies

As we say, matricies support element wise operaitons. 

Above, we used the addition operation, which added a scalar to all of the elements in the matrix/vector. 

Other operaitons are possible, including division, multiplication etc.

Element wise operations also work when operation on two matricies, as long as they are the same shape

## Matrix Product

The `matmul` (_matrix multiply_) operation is used to preform the Matrix Product. 

**Note**: When matricies are two dimensional, the `dot` operation yeilds the same result. For higher dimensions however there is a difference.

**Note**: The only safe time to use a Transpose is when data is arranged in rows of the oprigonal matricies

# Numpy Exam

In [26]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(input_array) 

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min /np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
  
 


def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    
    if m1.shape[0] != m2.shape[1] and m1.shape[1] != m2.shape[0]:     
        return False
    
    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
      
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)        
    else:
        return np.matmul(m2, m1)  
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list

    return sum(values)/len(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[ 0.     0.375  1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
